config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root 'orders#index'

  namespace :admin do
    resources :dishes, except: :show
  end
  resources :orders, except: :show
  resources :dashboards

  namespace :api do
    namespace :v1 do
      get 'user_orders' => 'user_orders#index'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord
  mount_uploader :image, DishImageUploader

  COURSES = %w(first_course main_course drink).freeze

  has_many :orders_dishes
  has_many :orders, through: :orders_dishes

  scope :first_courses, -> { where(course: 'first_course') }
  scope :main_courses, -> { where(course: 'main_course') }
  scope :drinks, -> { where(course: 'drink') }

  before_create :set_default_date

  validates :name, presence: true
  validates :price, presence: true

  def self.courses
    COURSES
  end

  private

  def set_default_date
    self.available_at = Date.today
  end
end

app/models/lunch_company.rb
class LunchCompany < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :orders_dishes
  has_many :dishes, through: :orders_dishes
  belongs_to :user

  before_create :set_default_date

  def add_dish(id:, course:)
    self.dishes << Dish.find_by(id: id, course: course)
  end

  private

  def set_default_date
    self.ordered_at = Date.today
  end
end

app/models/orders_dish.rb
class OrdersDish < ApplicationRecord
  belongs_to :dish
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  before_create :first_user_is_admin

  has_many :orders

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def first_user_is_admin
    return unless Rails.configuration.first_user_is_admin
    self.admin = true if User.count.zero?
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin

  protected

  def check_admin
    redirect_to root_path, alert: 'Forbidden.' unless current_user.admin?
  end
end

app/controllers/admin/dishes_controller.rb
class Admin::DishesController < Admin::BaseController
  before_action :find_dish, only: %i[show edit update destroy]
  before_action :find_all_dishes, only: %i[edit index show]

  def index; end

  def new
    @dish = Dish.new
  end

  def create
    @dish = Dish.new(dish_params)

    if @dish.save
      redirect_to admin_dishes_url,
                  notice: I18n.t('model_was_successfully_created',
                                 model_name: @dish.course.humanize)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @dish.update(dish_params)
      redirect_to admin_dishes_url,
                  notice: I18n.t('model_was_successfully_updated',
                                 model_name: @dish.course.humanize)
    else
      render :edit
    end
  end

  def destroy
    @dish.destroy
    redirect_to admin_dishes_url,
                notice: I18n.t('model_was_successfully_destroyed',
                               model_name: @dish.course.humanize)
  end

  private

  def find_dish
    @dish = Dish.find(params[:id])
  end

  def find_all_dishes
    @dishes = Dish.where(available_at: Date.today)
  end

  def dish_params
    params.require(:dish).permit(:name, :price, :course, :image)
  end
end

app/controllers/api/v1/user_orders_controller.rb
class Api::V1::UserOrdersController < ActionController::API
  before_action :check_lunch_company

  def index
    @orders = Order.where(ordered_at: Date.today)

    render 'api/v1/user_orders/index.json.jbuilder', status: 200
  end

  private

  def check_lunch_company
    render json: {}, status: 403 unless LunchCompany.find_by(token: request.headers[:token])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @date_range = ((Date.today - 2.weeks)..Date.today)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :find_order, only: %i[show edit update destroy]
  before_action :find_all_dishes, only: %i[new index show]

  def index
    @order = Order.new
    @orders = Order.where(
      user: current_user,
      ordered_at: params[:date].present? ? params[:date] : Date.today
    ).reverse
  end

  def show; end

  def create
    @order = current_user.orders.build
    @order.add_dish(id: order_params[:first_course_id], course: 'first_course')
    @order.add_dish(id: order_params[:main_course_id], course: 'main_course')
    @order.add_dish(id: order_params[:drink_id], course: 'drink')

    if @order.save
      redirect_to orders_url,
                  notice: I18n.t('model_was_successfully_created',
                                 model_name: @order.model_name.human)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @order.update(dish_params)
      redirect_to orders_url,
                  notice: I18n.t('model_was_successfully_updated',
                                 model_name: @order.model_name.human)
    else
      render :edit
    end
  end

  def destroy
    @order.destroy
    redirect_to orders_url,
                notice: I18n.t('model_was_successfully_destroyed',
                               model_name: @order.model_name.human)
  end

  private

  def find_order
    @order = current_user.orders.find_by(
      id: params[:id],
      ordered_at: Date.today
    )
  end

  def find_all_dishes
    @dishes = Dish.where(
      available_at: params[:date].present? ? params[:date] : Date.today
    )
  end

  def order_params
    params.require(:order).permit(:first_course_id, :main_course_id, :drink_id)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level.to_sym
    when :notice then 'alert alert-info'
    when :success then 'alert alert-success'
    when :error then 'alert alert-danger'
    when :alert then 'alert alert-danger'
    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/admin/dishes/_form.html.haml
- url = dish.persisted? ? admin_dish_path(dish) : admin_dishes_path

= simple_form_for dish&.becomes(Dish), url: url, html: { id: :dish_form } do |f|
  = f.error_notification
  = f.input :name
  = f.input :price
  = f.input :course do
    = f.select :course, Dish.courses.map { |course| [course.underscore.humanize, course] }, { include_blank: false }, class: 'form-control'
  = f.input :image, as: :file, input_html: { class: 'form-control' }

  .form-actions
    = f.button :submit

app/views/admin/dishes/_table.html.haml
%h3= dish_type
%table.table.table-striped{id: dish_type.parameterize(separator: '_')}
  %thead
    %tr
      %th Id
      %th Name
      %th Price
      %th Image
      %th Edit
      %th Destroy

  - dishes.each do |dish|
    %tbody
      %tr
        %td= dish.id
        %td= dish.name
        %td= dish.price
        %td= image_tag(dish.image.url, style: 'height: 140px') unless dish.image.blank?
        %td= link_to 'Edit', edit_admin_dish_path(dish.id)
        %td= link_to 'Destroy', admin_dish_path(dish.id), method: :delete

app/views/admin/dishes/edit.html.haml
= render 'form', dish: @dish

app/views/admin/dishes/index.html.haml
= link_to 'Create new dish', new_admin_dish_path, { style: 'float: right', class: 'btn btn-primary' }
%br

- if @dishes && @dishes.any?
  %br
  .row
    .col-xl-12
      = render 'table', dish_type: 'First Courses', dishes: @dishes.first_courses

  %br
  .row
    .col-xl-12
      = render 'table', dish_type: 'Drinks', dishes: @dishes.drinks

  %br
  .row
    .col-xl-12
      = render 'table', dish_type: 'Main Courses', dishes: @dishes.main_courses
- else
  = I18n.t('there_is_no_dishes')

app/views/admin/dishes/new.html.haml
= render 'form', dish: @dish

app/views/dashboards/_calendar.html.haml
%table.table.table-striped
  %thead
    %tr
      %th Weekday
      %th Date

  %tbody
    - date_range.reverse_each do |date|
      %tr
        %td= link_to date.strftime('%A'), orders_url(date: date)
        %td= link_to date.to_s, orders_url(date: date)

app/views/dashboards/index.html.haml
= render 'calendar', date_range: @date_range

app/views/layouts/_admin_nav_bar.html.haml
%ul.navbar-nav.mr-auto
  %li.nav-item
    = link_to('Profile', edit_user_registration_url, class: 'nav-link')
  %li.nav-item
    = link_to('Dashboard', dashboards_url, class: 'nav-link')
  %li.nav-item
    = link_to('Dishes', admin_dishes_url, class: 'nav-link')
  %li.nav-item
    = link_to('Orders', orders_url(date: Date.today), class: 'nav-link')

app/views/layouts/_user_nav_bar.html.haml
%ul.navbar-nav.mr-auto
  %li.nav-item
    = link_to('Profile', edit_user_registration_url, class: 'nav-link')
  %li.nav-item
    = link_to('Dashboard', dashboards_url, class: 'nav-link')
  %li.nav-item
    = link_to('Orders', orders_url(date: Date.today), class: 'nav-link')

app/views/layouts/application.html.haml
%html
  %head
    %title Lunch Ordering Saas
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    %nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
      .container
        = link_to 'LOS', '#', class: 'navbar-brand'
        %button.navbar-toggler{type: :button, 'data-toggle': 'collapse', 'aria-expanded': false, 'aria-label': 'Toggle navigation'}
          %span.navbar-toggler-icon

        .collapse.navbar-collapse
          - if current_user&.admin?
            = render 'layouts/admin_nav_bar'
          - else
            = render 'layouts/user_nav_bar'

        %form.form-inline.my-2.my-md-0
          = link_to('Logout', destroy_user_session_path, method: :delete) if current_user

    %br
    .container
      .row
        .col-lg-12
          = render 'shared/flash_messages', flash: flash
          = yield

app/views/orders/_form.html.haml
- if @dishes != nil && @dishes.first_courses.any? && @dishes.main_courses.any? && @dishes.drinks.any?

  = form_tag '/orders', method: :post, id: :order_form do
    %br
    .row
      .col-xl-12
        = render 'order_table', dish_name: 'First Courses', dish_type: 'first_course', dishes: @dishes.first_courses

    %br
    .row
      .col-xl-12
        = render 'order_table', dish_name: 'Drinks', dish_type: 'drink', dishes: @dishes.drinks

    %br
    .row
      .col-xl-12
        = render 'order_table', dish_name: 'Main Courses', dish_type: 'main_course', dishes: @dishes.main_courses

    = button_tag 'Create Order', type: :submit, name: :commit, class: 'btn btn-default', 'data-disable-with': 'Create Order'
- else
  %h5= I18n.t('we_do_not_have_available_dishes_right_now')

app/views/orders/_order_table.html.haml
%h3= dish_name
%table.table.table-striped
  %thead
    %tr
      %th Choose
      %th Name
      %th Price
      %th Image
  %tbody
    - dishes.each_with_index do |dish, i|
      %tr.option
        %td= radio_button_tag("order[#{dish_type}_id]", dish.id, checked = i.zero?)
        %td= dish.name
        %td= dish.price
        %td= image_tag(dish.image.url, style: 'height: 140px') unless dish.image.blank?

app/views/orders/_ordered_dishes_table.html.haml
%table.table.table-striped
  %thead
    %tr
      %th Dish
      %th Name
      %th Price
      %th Image

  - order.dishes.each do |dish|
    %tbody
      %tr
        %td= dish.course.humanize
        %td= dish.name
        %td= dish.price
        %td= image_tag(dish.image.url, style: 'height: 140px') unless dish.image.blank?

app/views/orders/index.html.haml
- date = params[:date].present? ? params[:date] : Date.today.to_s

= link_to 'Create new order for ' + Date.today.to_s, new_order_path, { style: 'float: right', class: 'btn btn-primary' }

- if @orders&.any?
  %br
  %h3= I18n.t('your_ordered_menus', date: date)
  - @orders.each do |order|
    %br
    = link_to 'Destroy', order_path(order.id), method: :delete, style: 'float: right' if date == Date.today.to_s
    = render 'ordered_dishes_table', order: order
- else
  %h3= I18n.t('you_do_not_have_ordered_menus', date: date)

app/views/orders/new.html.haml
= render 'form', dish: @dishes

app/views/shared/_flash_messages.html.haml
- flash.each do |key, value|
  .alert-dismissable{class: flash_class(key)}
    = link_to '×', '#', class: 'close', data: { dismiss: 'alert', label: 'close' }
    = value